= Development

Before start working on the AWS Service Operator please read the
link:contributing.adoc[Contributing Guidelines].

Make sure you first have all the dependencies installed. The source checkout
should be under your $GOPATH/src directory.

Checkout project or if you have forked it move it under github.com/awslabs
[source,shell]
----
cd $GOPATH/src/github.com/awslabs/aws-service-operator
----

If you want to make changes to the operators, they are all generated code, to
modify them you will need to install the `aws-operator-codegen` project by
running.

[source,shell]
----
make install-aws-codegen
----

After you have this installed you can run the following from the root of the
project.

[source,shell]
----
make rebuild
----

This takes the model files that are in `models/` and converts them into the
operator code in `pkg/operator` following that it will run the Kubernetes code
generation libraries to auto generate the `pkg/client`.

After have made sure the codegen is run you can then build the package and
run it against a remote cluster by passing in the `kubeconfig` file.

For local development start k8s cluster using
You can use link:https://kind.sigs.k8s.io/docs/user/quick-start/[kind]
or link:https://kubernetes.io/docs/tasks/tools/install-minikube[minikube]
for development

[source,shell]
----
kind create cluster
kubectl apply -f configs/aws-service-operator.yaml
----

Now you can run the aws-service-operator

[source,shell]
----
./aws-service-operator server --kubeconfig ~/.kube/config --region us-east-2 --bucket aws.service.operator.state.seizadi.infoblox.com
----

Try to create a resource
[source,shell]
----
kubectl apply -f examples/s3bucket.yaml
----

== Writing Additional Operators

Additional Custom Resource Definitions and Controllers can be created and
deployed using the build in model file to controller logic. Because each
resource is defined using Cloudformation we have a simple to use DSL for adding
additional resources.

To Add a resource start by create a model, we will follow adding a VPC so we will
add ./model/vpc.yaml

[source,yaml]
----
apiVersion: service-operator.aws/v1alpha1
kind: ModelDefinition
metadata:
  name: VpcResource
spec:
  kind: Vpc
  type: Spec # can be Spec or Data
  queue: true
  useCloudFormation: true
  resource:
    name: vpc
    plural: vpcs
    scope: Namespaced
  body:
    schema:
      title: Vpc
      type: object
      properties:
        - key: cidr
          type: string
          description: |
            Network IP CIDR to be created, e.g. 172.21.64.0/21.
          structKey: Cidr
          templateKey: Cidr
  output:
    schema:
      type: object
      properties:
        - key: vpnARN
          type: string
          description: |
            The VPC ARN for the AWS resource.
          structKey: VpnARN
          templateKey: VpnARN
----
Now we can run the aws-service-operator-codegen tool
[source,bash]
----
make aws-codegen
----
or
[source,bash]
----
make rebuild
----

The code generator will generate a number of new code packages to handle VPC:
[source,bash]
        new file:   models/vpc.yaml
        new file:   pkg/apis/service-operator.aws/v1alpha1/vpc.go
        new file:   pkg/client/clientset/versioned/typed/service-operator.aws/v1alpha1/fake/fake_vpc.go
        new file:   pkg/client/clientset/versioned/typed/service-operator.aws/v1alpha1/vpc.go
        new file:   pkg/client/informers/externalversions/service-operator.aws/v1alpha1/vpc.go
        new file:   pkg/client/listers/service-operator.aws/v1alpha1/vpc.go
        new file:   pkg/operators/vpc/cft.go
        new file:   pkg/operators/vpc/operator.go
----

It will also update existing code to include VPC model support:
[source,bash]
...
        modified:   pkg/operators/base/base.go
        modified:   pkg/helpers/template_functions.go
        modified:   configs/aws-service-operator.yaml
        modified:   pkg/apis/service-operator.aws/v1alpha1/zz_generated.deepcopy.go
        modified:   pkg/client/clientset/versioned/typed/service-operator.aws/v1alpha1/generated_expansion.go
        modified:   pkg/client/clientset/versioned/typed/service-operator.aws/v1alpha1/service-operator.aws_client.go
        modified:   pkg/client/informers/externalversions/generic.go
        modified:   pkg/client/informers/externalversions/service-operator.aws/v1alpha1/interface.go
        modified:   pkg/client/listers/service-operator.aws/v1alpha1/expansion_generated.go
----

Note the entry points entries for vpc resource in ./pkg/operators/base.go

In addition to the models/vpc.model we need to provide the corresponding Cloud Formation
Template in the examples/cloudformationtemplates/vpc.yaml The parameters and outputs in
model should match the Cloud Formation Template.

=== TODO Helm Chart
There is work to make sure Helm Chart is updated for any new changes, mainly CRD changes
for installation and updating the version and the image.

== Operator Lifecycle
The best place to start would be pkg/operators/base.go where each of the CR operators are
started, for example below you see the code to start the operator for VPC CR:
[source,go]
----
func (b *base) Watch(ctx context.Context, namespace string) {
	//....
		if b.config.Resources["vpc"] {
		go b.vpc.StartWatch(ctx, namespace)
	}
	//....
}
----
Note that you can configure which of the CR controllers run with config.Resources, so for this
new CR we need to configure it to run in init() from main.go:
[source,go]
----
func init() {
	//....
	rootCmd.PersistentFlags().StringVarP(&resources, "resources", "", "cloudformationtemplate,dynamodb,ecrrepository,elasticache,s3bucket,snssubscription,snstopic,sqsqueue,vpc", "Comma delimited list of CRDs to deploy")
	//....
}
----



== Getting this to work with VS or Goland IDEs

This is a standard Go project with Go Module support so the only customization would
be to setup the debugger, which is to setup project to build following Makefile build target:

[source,shell]
----
go build -ldflags "-X main.commit=$(commitSHA) -X main.date=$(dateStr)" ./cmd/aws-service-operator
----

For Goland IDE

Environment Variables:
[source,shell]
----
AWS_ID=$(shell aws configure get aws_access_key_id);AWS_SECRET_ACCESS_KEY=$(shell aws configure get aws_secret_access_key);AWS_REGION=us-east-2----
----

Go tool Arguments:
[source,shell]
----
-i -ldflags "-X main.commit=seizadi-dev -X main.date=1583889395"
----

Program Arguments:
[source,shell]
----
server --kubeconfig /Users/seizadi/.kube/config --region us-east-2 --bucket aws.service.operator.state.seizadi.infoblox.com
----
