// >>>>>>> DO NOT EDIT THIS FILE <<<<<<<<<<
// This file is autogenerated via `aws-operator-codegen process`
// If you'd like the change anything about this file make edits to the .templ
// file in the pkg/codegen/assets directory.

package vpc

import (
	"errors"
	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/service/cloudformation"
	awsV1alpha1 "github.com/awslabs/aws-service-operator/pkg/apis/service-operator.aws/v1alpha1"
	"github.com/awslabs/aws-service-operator/pkg/config"
	"github.com/awslabs/aws-service-operator/pkg/helpers"
)

// New generates a new object
func New(config config.Config, vpc *awsV1alpha1.Vpc, topicARN string) *Cloudformation {
	return &Cloudformation{
		Vpc:      vpc,
		config:   config,
		topicARN: topicARN,
	}
}

// Cloudformation defines the vpc cfts
type Cloudformation struct {
	config   config.Config
	Vpc      *awsV1alpha1.Vpc
	topicARN string
}

// StackName returns the name of the stack based on the aws-operator-config
func (s *Cloudformation) StackName() string {
	return helpers.StackName(s.config.ClusterName, "vpc", s.Vpc.Name, s.Vpc.Namespace)
}

// GetOutputs return the stack outputs from the DescribeStacks call
func (s *Cloudformation) GetOutputs() (map[string]string, error) {
	outputs := map[string]string{}
	sess := s.config.AWSSession
	svc := cloudformation.New(sess)

	stackInputs := cloudformation.DescribeStacksInput{
		StackName: aws.String(s.StackName()),
	}

	output, err := svc.DescribeStacks(&stackInputs)
	if err != nil {
		return nil, err
	}
	// Not sure if this is even possible
	if len(output.Stacks) != 1 {
		return nil, errors.New("no stacks returned with that stack name")
	}

	for _, out := range output.Stacks[0].Outputs {
		outputs[*out.OutputKey] = *out.OutputValue
	}

	return outputs, err
}

// CreateStack will create the stack with the supplied params
func (s *Cloudformation) CreateStack() (output *cloudformation.CreateStackOutput, err error) {
	sess := s.config.AWSSession
	svc := cloudformation.New(sess)

	cftemplate := helpers.GetCloudFormationTemplate(s.config, "vpc", s.Vpc.Spec.CloudFormationTemplateName, s.Vpc.Spec.CloudFormationTemplateNamespace)

	stackInputs := cloudformation.CreateStackInput{
		StackName:   aws.String(s.StackName()),
		TemplateURL: aws.String(cftemplate),
		NotificationARNs: []*string{
			aws.String(s.topicARN),
		},
	}

	resourceName := helpers.CreateParam("ResourceName", s.Vpc.Name)
	resourceVersion := helpers.CreateParam("ResourceVersion", s.Vpc.ResourceVersion)
	namespace := helpers.CreateParam("Namespace", s.Vpc.Namespace)
	clusterName := helpers.CreateParam("ClusterName", s.config.ClusterName)
	stackNameTemp := "{{.Obj.Spec.StackName}}"
	stackNameValue, err := helpers.Templatize(stackNameTemp, helpers.Data{Obj: s.Vpc, Config: s.config, Helpers: helpers.New()})
	if err != nil {
		return output, err
	}
	stackName := helpers.CreateParam("StackName", helpers.Stringify(stackNameValue))
	vpcCIDRTemp := "{{.Obj.Spec.VpcCIDR}}"
	vpcCIDRValue, err := helpers.Templatize(vpcCIDRTemp, helpers.Data{Obj: s.Vpc, Config: s.config, Helpers: helpers.New()})
	if err != nil {
		return output, err
	}
	vpcCIDR := helpers.CreateParam("VpcCIDR", helpers.Stringify(vpcCIDRValue))
	envTemp := "{{.Obj.Spec.Env}}"
	envValue, err := helpers.Templatize(envTemp, helpers.Data{Obj: s.Vpc, Config: s.config, Helpers: helpers.New()})
	if err != nil {
		return output, err
	}
	env := helpers.CreateParam("Env", helpers.Stringify(envValue))
	jenkinsPeerEnableTemp := "{{.Obj.Spec.JenkinsPeerEnable}}"
	jenkinsPeerEnableValue, err := helpers.Templatize(jenkinsPeerEnableTemp, helpers.Data{Obj: s.Vpc, Config: s.config, Helpers: helpers.New()})
	if err != nil {
		return output, err
	}
	jenkinsPeerEnable := helpers.CreateParam("JenkinsPeerEnable", helpers.Stringify(jenkinsPeerEnableValue))
	jenkinsPeerPropertiesTemp := "{{.Obj.Spec.JenkinsPeerProperties}}"
	jenkinsPeerPropertiesValue, err := helpers.Templatize(jenkinsPeerPropertiesTemp, helpers.Data{Obj: s.Vpc, Config: s.config, Helpers: helpers.New()})
	if err != nil {
		return output, err
	}
	jenkinsPeerProperties := helpers.CreateParam("JenkinsPeerProperties", helpers.Stringify(jenkinsPeerPropertiesValue))
	rdsPeerEnableTemp := "{{.Obj.Spec.RDSPeerEnable}}"
	rdsPeerEnableValue, err := helpers.Templatize(rdsPeerEnableTemp, helpers.Data{Obj: s.Vpc, Config: s.config, Helpers: helpers.New()})
	if err != nil {
		return output, err
	}
	rdsPeerEnable := helpers.CreateParam("RDSPeerEnable", helpers.Stringify(rdsPeerEnableValue))
	rdsPeerPropertiesTemp := "{{.Obj.Spec.RDSPeerProperties}}"
	rdsPeerPropertiesValue, err := helpers.Templatize(rdsPeerPropertiesTemp, helpers.Data{Obj: s.Vpc, Config: s.config, Helpers: helpers.New()})
	if err != nil {
		return output, err
	}
	rdsPeerProperties := helpers.CreateParam("RDSPeerProperties", helpers.Stringify(rdsPeerPropertiesValue))
	redisPeerEnableTemp := "{{.Obj.Spec.RedisPeerEnable}}"
	redisPeerEnableValue, err := helpers.Templatize(redisPeerEnableTemp, helpers.Data{Obj: s.Vpc, Config: s.config, Helpers: helpers.New()})
	if err != nil {
		return output, err
	}
	redisPeerEnable := helpers.CreateParam("RedisPeerEnable", helpers.Stringify(redisPeerEnableValue))
	redisPeerPropertiesTemp := "{{.Obj.Spec.RedisPeerProperties}}"
	redisPeerPropertiesValue, err := helpers.Templatize(redisPeerPropertiesTemp, helpers.Data{Obj: s.Vpc, Config: s.config, Helpers: helpers.New()})
	if err != nil {
		return output, err
	}
	redisPeerProperties := helpers.CreateParam("RedisPeerProperties", helpers.Stringify(redisPeerPropertiesValue))
	tidePeerEnableTemp := "{{.Obj.Spec.TIDEPeerEnable}}"
	tidePeerEnableValue, err := helpers.Templatize(tidePeerEnableTemp, helpers.Data{Obj: s.Vpc, Config: s.config, Helpers: helpers.New()})
	if err != nil {
		return output, err
	}
	tidePeerEnable := helpers.CreateParam("TIDEPeerEnable", helpers.Stringify(tidePeerEnableValue))
	tidePeerPropertiesTemp := "{{.Obj.Spec.TIDEPeerProperties}}"
	tidePeerPropertiesValue, err := helpers.Templatize(tidePeerPropertiesTemp, helpers.Data{Obj: s.Vpc, Config: s.config, Helpers: helpers.New()})
	if err != nil {
		return output, err
	}
	tidePeerProperties := helpers.CreateParam("TIDEPeerProperties", helpers.Stringify(tidePeerPropertiesValue))
	bastionPeerPropertiesTemp := "{{.Obj.Spec.BastionPeerProperties}}"
	bastionPeerPropertiesValue, err := helpers.Templatize(bastionPeerPropertiesTemp, helpers.Data{Obj: s.Vpc, Config: s.config, Helpers: helpers.New()})
	if err != nil {
		return output, err
	}
	bastionPeerProperties := helpers.CreateParam("BastionPeerProperties", helpers.Stringify(bastionPeerPropertiesValue))
	wbr1Temp := "{{.Obj.Spec.WBR1}}"
	wbr1Value, err := helpers.Templatize(wbr1Temp, helpers.Data{Obj: s.Vpc, Config: s.config, Helpers: helpers.New()})
	if err != nil {
		return output, err
	}
	wbr1 := helpers.CreateParam("WBR1", helpers.Stringify(wbr1Value))
	wbr2Temp := "{{.Obj.Spec.WBR2}}"
	wbr2Value, err := helpers.Templatize(wbr2Temp, helpers.Data{Obj: s.Vpc, Config: s.config, Helpers: helpers.New()})
	if err != nil {
		return output, err
	}
	wbr2 := helpers.CreateParam("WBR2", helpers.Stringify(wbr2Value))
	azIndexListTemp := "{{.Obj.Spec.AzIndexList}}"
	azIndexListValue, err := helpers.Templatize(azIndexListTemp, helpers.Data{Obj: s.Vpc, Config: s.config, Helpers: helpers.New()})
	if err != nil {
		return output, err
	}
	azIndexList := helpers.CreateParam("AzIndexList", helpers.Stringify(azIndexListValue))

	parameters := []*cloudformation.Parameter{}
	parameters = append(parameters, resourceName)
	parameters = append(parameters, resourceVersion)
	parameters = append(parameters, namespace)
	parameters = append(parameters, clusterName)
	parameters = append(parameters, stackName)
	parameters = append(parameters, vpcCIDR)
	parameters = append(parameters, env)
	parameters = append(parameters, jenkinsPeerEnable)
	parameters = append(parameters, jenkinsPeerProperties)
	parameters = append(parameters, rdsPeerEnable)
	parameters = append(parameters, rdsPeerProperties)
	parameters = append(parameters, redisPeerEnable)
	parameters = append(parameters, redisPeerProperties)
	parameters = append(parameters, tidePeerEnable)
	parameters = append(parameters, tidePeerProperties)
	parameters = append(parameters, bastionPeerProperties)
	parameters = append(parameters, wbr1)
	parameters = append(parameters, wbr2)
	parameters = append(parameters, azIndexList)

	stackInputs.SetParameters(parameters)

	resourceNameTag := helpers.CreateTag("ResourceName", s.Vpc.Name)
	resourceVersionTag := helpers.CreateTag("ResourceVersion", s.Vpc.ResourceVersion)
	namespaceTag := helpers.CreateTag("Namespace", s.Vpc.Namespace)
	clusterNameTag := helpers.CreateTag("ClusterName", s.config.ClusterName)

	tags := []*cloudformation.Tag{}
	tags = append(tags, resourceNameTag)
	tags = append(tags, resourceVersionTag)
	tags = append(tags, namespaceTag)
	tags = append(tags, clusterNameTag)

	stackInputs.SetTags(tags)

	output, err = svc.CreateStack(&stackInputs)
	return
}

// UpdateStack will update the existing stack
func (s *Cloudformation) UpdateStack(updated *awsV1alpha1.Vpc) (output *cloudformation.UpdateStackOutput, err error) {
	sess := s.config.AWSSession
	svc := cloudformation.New(sess)

	cftemplate := helpers.GetCloudFormationTemplate(s.config, "vpc", updated.Spec.CloudFormationTemplateName, updated.Spec.CloudFormationTemplateNamespace)

	stackInputs := cloudformation.UpdateStackInput{
		StackName:   aws.String(s.StackName()),
		TemplateURL: aws.String(cftemplate),
		NotificationARNs: []*string{
			aws.String(s.topicARN),
		},
	}

	resourceName := helpers.CreateParam("ResourceName", s.Vpc.Name)
	resourceVersion := helpers.CreateParam("ResourceVersion", s.Vpc.ResourceVersion)
	namespace := helpers.CreateParam("Namespace", s.Vpc.Namespace)
	clusterName := helpers.CreateParam("ClusterName", s.config.ClusterName)
	stackNameTemp := "{{.Obj.Spec.StackName}}"
	stackNameValue, err := helpers.Templatize(stackNameTemp, helpers.Data{Obj: updated, Config: s.config, Helpers: helpers.New()})
	if err != nil {
		return output, err
	}
	stackName := helpers.CreateParam("StackName", helpers.Stringify(stackNameValue))
	vpcCIDRTemp := "{{.Obj.Spec.VpcCIDR}}"
	vpcCIDRValue, err := helpers.Templatize(vpcCIDRTemp, helpers.Data{Obj: updated, Config: s.config, Helpers: helpers.New()})
	if err != nil {
		return output, err
	}
	vpcCIDR := helpers.CreateParam("VpcCIDR", helpers.Stringify(vpcCIDRValue))
	envTemp := "{{.Obj.Spec.Env}}"
	envValue, err := helpers.Templatize(envTemp, helpers.Data{Obj: updated, Config: s.config, Helpers: helpers.New()})
	if err != nil {
		return output, err
	}
	env := helpers.CreateParam("Env", helpers.Stringify(envValue))
	jenkinsPeerEnableTemp := "{{.Obj.Spec.JenkinsPeerEnable}}"
	jenkinsPeerEnableValue, err := helpers.Templatize(jenkinsPeerEnableTemp, helpers.Data{Obj: updated, Config: s.config, Helpers: helpers.New()})
	if err != nil {
		return output, err
	}
	jenkinsPeerEnable := helpers.CreateParam("JenkinsPeerEnable", helpers.Stringify(jenkinsPeerEnableValue))
	jenkinsPeerPropertiesTemp := "{{.Obj.Spec.JenkinsPeerProperties}}"
	jenkinsPeerPropertiesValue, err := helpers.Templatize(jenkinsPeerPropertiesTemp, helpers.Data{Obj: updated, Config: s.config, Helpers: helpers.New()})
	if err != nil {
		return output, err
	}
	jenkinsPeerProperties := helpers.CreateParam("JenkinsPeerProperties", helpers.Stringify(jenkinsPeerPropertiesValue))
	rdsPeerEnableTemp := "{{.Obj.Spec.RDSPeerEnable}}"
	rdsPeerEnableValue, err := helpers.Templatize(rdsPeerEnableTemp, helpers.Data{Obj: updated, Config: s.config, Helpers: helpers.New()})
	if err != nil {
		return output, err
	}
	rdsPeerEnable := helpers.CreateParam("RDSPeerEnable", helpers.Stringify(rdsPeerEnableValue))
	rdsPeerPropertiesTemp := "{{.Obj.Spec.RDSPeerProperties}}"
	rdsPeerPropertiesValue, err := helpers.Templatize(rdsPeerPropertiesTemp, helpers.Data{Obj: updated, Config: s.config, Helpers: helpers.New()})
	if err != nil {
		return output, err
	}
	rdsPeerProperties := helpers.CreateParam("RDSPeerProperties", helpers.Stringify(rdsPeerPropertiesValue))
	redisPeerEnableTemp := "{{.Obj.Spec.RedisPeerEnable}}"
	redisPeerEnableValue, err := helpers.Templatize(redisPeerEnableTemp, helpers.Data{Obj: updated, Config: s.config, Helpers: helpers.New()})
	if err != nil {
		return output, err
	}
	redisPeerEnable := helpers.CreateParam("RedisPeerEnable", helpers.Stringify(redisPeerEnableValue))
	redisPeerPropertiesTemp := "{{.Obj.Spec.RedisPeerProperties}}"
	redisPeerPropertiesValue, err := helpers.Templatize(redisPeerPropertiesTemp, helpers.Data{Obj: updated, Config: s.config, Helpers: helpers.New()})
	if err != nil {
		return output, err
	}
	redisPeerProperties := helpers.CreateParam("RedisPeerProperties", helpers.Stringify(redisPeerPropertiesValue))
	tidePeerEnableTemp := "{{.Obj.Spec.TIDEPeerEnable}}"
	tidePeerEnableValue, err := helpers.Templatize(tidePeerEnableTemp, helpers.Data{Obj: updated, Config: s.config, Helpers: helpers.New()})
	if err != nil {
		return output, err
	}
	tidePeerEnable := helpers.CreateParam("TIDEPeerEnable", helpers.Stringify(tidePeerEnableValue))
	tidePeerPropertiesTemp := "{{.Obj.Spec.TIDEPeerProperties}}"
	tidePeerPropertiesValue, err := helpers.Templatize(tidePeerPropertiesTemp, helpers.Data{Obj: updated, Config: s.config, Helpers: helpers.New()})
	if err != nil {
		return output, err
	}
	tidePeerProperties := helpers.CreateParam("TIDEPeerProperties", helpers.Stringify(tidePeerPropertiesValue))
	bastionPeerPropertiesTemp := "{{.Obj.Spec.BastionPeerProperties}}"
	bastionPeerPropertiesValue, err := helpers.Templatize(bastionPeerPropertiesTemp, helpers.Data{Obj: updated, Config: s.config, Helpers: helpers.New()})
	if err != nil {
		return output, err
	}
	bastionPeerProperties := helpers.CreateParam("BastionPeerProperties", helpers.Stringify(bastionPeerPropertiesValue))
	wbr1Temp := "{{.Obj.Spec.WBR1}}"
	wbr1Value, err := helpers.Templatize(wbr1Temp, helpers.Data{Obj: updated, Config: s.config, Helpers: helpers.New()})
	if err != nil {
		return output, err
	}
	wbr1 := helpers.CreateParam("WBR1", helpers.Stringify(wbr1Value))
	wbr2Temp := "{{.Obj.Spec.WBR2}}"
	wbr2Value, err := helpers.Templatize(wbr2Temp, helpers.Data{Obj: updated, Config: s.config, Helpers: helpers.New()})
	if err != nil {
		return output, err
	}
	wbr2 := helpers.CreateParam("WBR2", helpers.Stringify(wbr2Value))
	azIndexListTemp := "{{.Obj.Spec.AzIndexList}}"
	azIndexListValue, err := helpers.Templatize(azIndexListTemp, helpers.Data{Obj: updated, Config: s.config, Helpers: helpers.New()})
	if err != nil {
		return output, err
	}
	azIndexList := helpers.CreateParam("AzIndexList", helpers.Stringify(azIndexListValue))

	parameters := []*cloudformation.Parameter{}
	parameters = append(parameters, resourceName)
	parameters = append(parameters, resourceVersion)
	parameters = append(parameters, namespace)
	parameters = append(parameters, clusterName)
	parameters = append(parameters, stackName)
	parameters = append(parameters, vpcCIDR)
	parameters = append(parameters, env)
	parameters = append(parameters, jenkinsPeerEnable)
	parameters = append(parameters, jenkinsPeerProperties)
	parameters = append(parameters, rdsPeerEnable)
	parameters = append(parameters, rdsPeerProperties)
	parameters = append(parameters, redisPeerEnable)
	parameters = append(parameters, redisPeerProperties)
	parameters = append(parameters, tidePeerEnable)
	parameters = append(parameters, tidePeerProperties)
	parameters = append(parameters, bastionPeerProperties)
	parameters = append(parameters, wbr1)
	parameters = append(parameters, wbr2)
	parameters = append(parameters, azIndexList)

	stackInputs.SetParameters(parameters)

	resourceNameTag := helpers.CreateTag("ResourceName", s.Vpc.Name)
	resourceVersionTag := helpers.CreateTag("ResourceVersion", s.Vpc.ResourceVersion)
	namespaceTag := helpers.CreateTag("Namespace", s.Vpc.Namespace)
	clusterNameTag := helpers.CreateTag("ClusterName", s.config.ClusterName)

	tags := []*cloudformation.Tag{}
	tags = append(tags, resourceNameTag)
	tags = append(tags, resourceVersionTag)
	tags = append(tags, namespaceTag)
	tags = append(tags, clusterNameTag)

	stackInputs.SetTags(tags)

	output, err = svc.UpdateStack(&stackInputs)
	return
}

// DeleteStack will delete the stack
func (s *Cloudformation) DeleteStack() (err error) {
	sess := s.config.AWSSession
	svc := cloudformation.New(sess)

	stackInputs := cloudformation.DeleteStackInput{}
	stackInputs.SetStackName(s.StackName())

	_, err = svc.DeleteStack(&stackInputs)
	return
}

// WaitUntilStackDeleted will delete the stack
func (s *Cloudformation) WaitUntilStackDeleted() (err error) {
	sess := s.config.AWSSession
	svc := cloudformation.New(sess)

	stackInputs := cloudformation.DescribeStacksInput{
		StackName: aws.String(s.StackName()),
	}

	err = svc.WaitUntilStackDeleteComplete(&stackInputs)
	return
}
